[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simsoword"
version = "0.1.0"
description = "A phonetic similarity package for comparing words"
authors = [
    {name = "Manish Prajapati"}
]
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "jellyfish"
]